db.transport.url=jdbc:mysql://localhost:3306/transport
db.racing.url=jdbc:mysql://localhost:3306/racing
db.booking.url=jdbc:mysql://localhost:3306/booking
db.struct.url=jdbc:mysql://localhost:3306/struct
db.user=root
db.password=secret
